###
# Run `brew bundle` in this directory to install all of this stuff
###

cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'grc' # colourize log commands (e.g. ``grc tail /var/log/syslog`)
brew 'imagemagick'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'tree'
brew 'fzf'
brew 'fasd'
brew 'source-highlight' # for `less` highlighting (see zsh config)
brew 'lesspipe'
brew 'readline'
brew 'unrar'
brew 'wget'
brew 'ffmpeg' # for youtube-dl post-processing
brew 'youtube-dl' # download Youtube (and other) videos


###
# Development
###

# searching
brew 'the_silver_searcher' # ag
brew 'the_platinum_searcher' # pt
brew 'sift'

# programming languages
cask 'java'
brew 'go'
brew 'node'
brew 'leiningen' # clojure
brew 'boot-clj' # clojure
brew 'haskell-stack'
brew 'erlang'
brew 'elixir'
brew 'scala'
brew 'sbt' # scala build tool
brew 'chruby'
brew 'ruby-install'

# DBs
brew 'postgresql'
brew 'mysql'

# editors
brew 'emacs'
tap 'neovim/neovim'
brew 'neovim'

# tools
brew 'heroku'
brew 'heroku-toolbelt'
brew 'docker'
cask 'docker' # docker-for-mac
brew 'docker-compose'
brew 'ctags'
brew 'jq'
brew 'tig' # git visualization
brew 'httpie' # smart curl replacement?

# fonts
tap 'caskroom/fonts'
# `mensch` font is great for programming, but it's not in caskroom/fonts :( http://robey.lag.net/2010/06/21/mensch-font.html
cask 'font-source-code-pro'
cask 'font-fira-code'
cask 'font-anonymous-pro'
cask 'font-terminus'
cask 'font-dejavu-sans'

###
# OSX applications
###
cask 'lastpass'
cask 'atom'
cask 'google-chrome'
cask 'slack'
cask 'transmission' # torrenting
cask 'vlc'
cask 'alfred' # spotlight replacement
cask 'iterm2'
cask 'karabiner' # keyboard mapping
cask 'seil' # rebind capslock
cask 'spotify'
cask 'spectacle' # window management
cask 'contexts' # command-tab replacement
cask 'goofy' # facebook messenger
cask 'flux' # blue light removal
cask 'smcfancontrol'
cask 'scroll-reverser'
cask 'caffeine' # control over screen locking
